# Generated by Django 2.0.5 on 2019-11-20 21:53

import json
import os

from django.conf import settings
from django.db import migrations


def get_data():
    file_path = os.path.join(
        settings.BASE_DIR,
        os.path.normpath('apps/base/books.json'))

    with open(file_path, mode='r') as file:
        file_content = file.read()
        data = json.loads(file_content)
        return data[0]


def forwards_func(apps, schema_editor):
    Book = apps.get_model('base', 'Book')
    Category = apps.get_model('base', 'Category')

    data = get_data()

    bulk_categories = []
    categories_indexed = {}
    for category in data['categories']:
        category_model = Category(id=category['id'], name=category['name'])
        bulk_categories.append(category_model)
        categories_indexed[category['id']] = category_model
    Category.objects.bulk_create(bulk_categories)

    bulk_books = []
    for book in data['books']:
        category = categories_indexed[book['category_id']]
        price = float(book['price'].replace('£', ''))
        bulk_books.append(
            Book(
                id=book['id'],
                title=book['title'],
                thumbnail_url=book['thumbnail_url'],
                price=price,
                stock=book['stock'],
                product_description=book['product_description'],
                upc=book['upc'],
                last_modified=None,
                category=category)
        )
    Book.objects.bulk_create(bulk_books)


def reverse_func(apps, schema_editor):
    Book = apps.get_model('base', 'Book')
    Category = apps.get_model('base', 'Category')

    Book.objects.all().delete()
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
